In [1]:
import json
from pathlib import Path

import polars as pl

In [2]:
raw_files = list(Path("../data/raw").glob("crossref_raw_*.json"))
raw_files

[WindowsPath('../data/raw/crossref_raw_20260616T222600Z_97eeaaa5-9aae-46be-b48b-083f0398bc35.json')]

In [3]:
raw_path = raw_files[-1]

with raw_path.open("r", encoding="utf-8") as file:
    payload = json.load(file)

items = payload["message"]["items"]

len(items)

200

In [4]:
items[0].keys()

dict_keys(['indexed', 'reference-count', 'publisher', 'issue', 'license', 'content-domain', 'short-container-title', 'published-print', 'DOI', 'type', 'created', 'page', 'source', 'is-referenced-by-count', 'title', 'prefix', 'volume', 'author', 'member', 'container-title', 'link', 'deposited', 'score', 'resource', 'issued', 'references-count', 'journal-issue', 'alternative-id', 'URL', 'ISSN', 'issn-type', 'published'])

In [5]:
items[0]

{'indexed': {'date-parts': [[2022, 3, 29]],
  'date-time': '2022-03-29T07:17:11Z',
  'timestamp': 1648538231791},
 'reference-count': 0,
 'publisher': 'Elsevier BV',
 'issue': '7',
 'license': [{'start': {'date-parts': [[2203, 10, 1]],
    'date-time': '2203-10-01T00:00:00Z',
    'timestamp': 7376313600000},
   'content-version': 'tdm',
   'delay-in-days': 0,
   'URL': 'https://www.elsevier.com/tdm/userlicense/1.0/'}],
 'content-domain': {'domain': [], 'crossmark-restriction': False},
 'short-container-title': ['Aten Primaria'],
 'published-print': {'date-parts': [[2203, 10]]},
 'DOI': '10.1157/13053457',
 'type': 'journal-article',
 'created': {'date-parts': [[2003, 11, 17]],
  'date-time': '2003-11-17T16:44:58Z',
  'timestamp': 1069087498000},
 'page': '437-437',
 'source': 'Crossref',
 'is-referenced-by-count': 1,
 'title': ['Prevalencia del uso preconcepcional del ácido fólico en el área norte de Pontevedra'],
 'prefix': '10.1016',
 'volume': '32',
 'author': [{'given': 'A',
   'family': 'Pérez-Vázquez',
   'sequence': 'first',
   'affiliation': [],
   'role': [{'role': 'author', 'vocabulary': 'crossref'}]},
  {'given': 'R',
   'family': 'Vidal Álvarez',
   'sequence': 'additional',
   'affiliation': [],
   'role': [{'role': 'author', 'vocabulary': 'crossref'}]},
  {'given': 'M',
   'family': 'Castro Pazos',
   'sequence': 'additional',
   'affiliation': [],
   'role': [{'role': 'author', 'vocabulary': 'crossref'}]},
  {'given': 'A',
   'family': 'Aulet Ruiz',
   'sequence': 'additional',
   'affiliation': [],
   'role': [{'role': 'author', 'vocabulary': 'crossref'}]}],
 'member': '78',
 'container-title': ['Atención Primaria'],
 'link': [{'URL': 'https://api.elsevier.com/content/article/PII:13002413?httpAccept=text/xml',
   'content-type': 'text/xml',
   'content-version': 'vor',
   'intended-application': 'text-mining'},
  {'URL': 'https://api.elsevier.com/content/article/PII:13002413?httpAccept=text/plain',
   'content-type': 'text/plain',
   'content-version': 'vor',
   'intended-application': 'text-mining'}],
 'deposited': {'date-parts': [[2019, 2, 17]],
  'date-time': '2019-02-17T01:23:25Z',
  'timestamp': 1550366605000},
 'score': 1.0,
 'resource': {'primary': {'URL': 'http://db.doyma.es/cgi-bin/wdbcgi.exe/doyma/mrevista.fulltext?pident=13053457'}},
 'issued': {'date-parts': [[2203, 10]]},
 'references-count': 0,
 'journal-issue': {'issue': '7'},
 'alternative-id': ['13002413'],
 'URL': 'https://doi.org/10.1157/13053457',
 'ISSN': ['0212-6567', '1578-1275'],
 'issn-type': [{'value': '0212-6567', 'type': 'print'},
  {'value': '1578-1275', 'type': 'electronic'}],
 'published': {'date-parts': [[2203, 10]]}}

In [6]:
all_keys = {}

for item in items:
    for key in item.keys():
        all_keys[key] = all_keys.get(key, 0) + 1

sorted(all_keys.items(), key=lambda x: x[1], reverse=True)

[('indexed', 200),
 ('reference-count', 200),
 ('publisher', 200),
 ('content-domain', 200),
 ('DOI', 200),
 ('type', 200),
 ('created', 200),
 ('source', 200),
 ('is-referenced-by-count', 200),
 ('prefix', 200),
 ('member', 200),
 ('deposited', 200),
 ('score', 200),
 ('resource', 200),
 ('issued', 200),
 ('references-count', 200),
 ('URL', 200),
 ('published', 200),
 ('container-title', 197),
 ('title', 196),
 ('ISSN', 177),
 ('issn-type', 177),
 ('author', 176),
 ('short-container-title', 172),
 ('published-print', 153),
 ('published-online', 128),
 ('volume', 115),
 ('page', 108),
 ('issue', 89),
 ('journal-issue', 89),
 ('link', 49),
 ('abstract', 31),
 ('alternative-id', 23),
 ('license', 22),
 ('edition-number', 20),
 ('isbn-type', 20),
 ('ISBN', 20),
 ('update-policy', 17),
 ('original-title', 8),
 ('language', 5),
 ('reference', 3),
 ('article-number', 1),
 ('assertion', 1)]

In [7]:
bronze_files = list(Path("../data/bronze").glob("bronze_crossref_works_*.parquet"))
bronze_path = bronze_files[-1]

df = pl.read_parquet(bronze_path)
df.head()

shape: (5, 15)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ doi       ┆ title     ┆ publicati ┆ publisher ┆ … ┆ url       ┆ authors_j ┆ raw_json  ┆ source   │
│ ---       ┆ ---       ┆ on_type   ┆ ---       ┆   ┆ ---       ┆ son       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ ---       ┆ str       ┆   ┆ str       ┆ ---       ┆ str       ┆ str      │
│           ┆           ┆ str       ┆           ┆   ┆           ┆ str       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 10.1157/1 ┆ Prevalenc ┆ journal-a ┆ Elsevier  ┆ … ┆ https://d ┆ [{"given" ┆ {"DOI":   ┆ crossref │
│ 3053457   ┆ ia del    ┆ rticle    ┆ BV        ┆   ┆ oi.org/10 ┆ : "A",    ┆ "10.1157/ ┆          │
│           ┆ uso preco ┆           ┆           ┆   ┆ .1157/130 ┆ "family": ┆ 13053457" ┆          │
│           ┆ ncepc…    ┆           ┆           ┆   ┆ 534…      ┆ "Pér…     ┆ , "I…     ┆          │
│ 10.1157/1 ┆ Mastopatí ┆ journal-a ┆ Elsevier  ┆ … ┆ https://d ┆ [{"given" ┆ {"DOI":   ┆ crossref │
│ 3053459   ┆ a tras    ┆ rticle    ┆ BV        ┆   ┆ oi.org/10 ┆ : "A",    ┆ "10.1157/ ┆          │
│           ┆ tratamien ┆           ┆           ┆   ┆ .1157/130 ┆ "family": ┆ 13053459" ┆          │
│           ┆ to co…    ┆           ┆           ┆   ┆ 534…      ┆ "Pie…     ┆ , "I…     ┆          │
│ 10.1157/1 ┆ Sonambuli ┆ journal-a ┆ Elsevier  ┆ … ┆ https://d ┆ [{"given" ┆ {"DOI":   ┆ crossref │
│ 3053456   ┆ smo       ┆ rticle    ┆ BV        ┆   ┆ oi.org/10 ┆ : "M",    ┆ "10.1157/ ┆          │
│           ┆ asociado  ┆           ┆           ┆   ┆ .1157/130 ┆ "family": ┆ 13053456" ┆          │
│           ┆ con zolp… ┆           ┆           ┆   ┆ 534…      ┆ "Yan…     ┆ , "I…     ┆          │
│ 10.1157/1 ┆ Respuesta ┆ journal-a ┆ Elsevier  ┆ … ┆ https://d ┆ [{"given" ┆ {"DOI":   ┆ crossref │
│ 3053452   ┆ de la     ┆ rticle    ┆ BV        ┆   ┆ oi.org/10 ┆ : "I",    ┆ "10.1157/ ┆          │
│           ┆ autora    ┆           ┆           ┆   ┆ .1157/130 ┆ "family": ┆ 13053452" ┆          │
│           ┆           ┆           ┆           ┆   ┆ 534…      ┆ "Fer…     ┆ , "I…     ┆          │
│ 10.1157/1 ┆ Hepatitis ┆ journal-a ┆ Elsevier  ┆ … ┆ https://d ┆ [{"given" ┆ {"DOI":   ┆ crossref │
│ 3053449   ┆ C: diagnó ┆ rticle    ┆ BV        ┆   ┆ oi.org/10 ┆ : "JI",   ┆ "10.1157/ ┆          │
│           ┆ stico y   ┆           ┆           ┆   ┆ .1157/130 ┆ "family": ┆ 13053449" ┆          │
│           ┆ pre…      ┆           ┆           ┆   ┆ 534…      ┆ "Al…      ┆ , "I…     ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [8]:
profile = []

for col in df.columns:
    profile.append({
        "column": col,
        "dtype": str(df[col].dtype),
        "nulls": df[col].null_count(),
        "null_percent": round(df[col].null_count() / df.height * 100, 2),
        "unique_values": df[col].n_unique(),
    })

pl.DataFrame(profile)

shape: (15, 5)
┌────────────────────────┬────────┬───────┬──────────────┬───────────────┐
│ column                 ┆ dtype  ┆ nulls ┆ null_percent ┆ unique_values │
│ ---                    ┆ ---    ┆ ---   ┆ ---          ┆ ---           │
│ str                    ┆ str    ┆ i64   ┆ f64          ┆ i64           │
╞════════════════════════╪════════╪═══════╪══════════════╪═══════════════╡
│ doi                    ┆ String ┆ 0     ┆ 0.0          ┆ 200           │
│ title                  ┆ String ┆ 4     ┆ 2.0          ┆ 195           │
│ publication_type       ┆ String ┆ 0     ┆ 0.0          ┆ 5             │
│ publisher              ┆ String ┆ 0     ┆ 0.0          ┆ 37            │
│ container_title        ┆ String ┆ 3     ┆ 1.5          ┆ 40            │
│ …                      ┆ …      ┆ …     ┆ …            ┆ …             │
│ is_referenced_by_count ┆ Int64  ┆ 0     ┆ 0.0          ┆ 18            │
│ url                    ┆ String ┆ 0     ┆ 0.0          ┆ 200           │
│ authors_json           ┆ String ┆ 0     ┆ 0.0          ┆ 176           │
│ raw_json               ┆ String ┆ 0     ┆ 0.0          ┆ 200           │
│ source                 ┆ String ┆ 0     ┆ 0.0          ┆ 1             │
└────────────────────────┴────────┴───────┴──────────────┴───────────────┘

In [6]:
item = items[0]

item.get("author")

[{'given': 'A',
  'family': 'Pérez-Vázquez',
  'sequence': 'first',
  'affiliation': [],
  'role': [{'role': 'author', 'vocabulary': 'crossref'}]},
 {'given': 'R',
  'family': 'Vidal Álvarez',
  'sequence': 'additional',
  'affiliation': [],
  'role': [{'role': 'author', 'vocabulary': 'crossref'}]},
 {'given': 'M',
  'family': 'Castro Pazos',
  'sequence': 'additional',
  'affiliation': [],
  'role': [{'role': 'author', 'vocabulary': 'crossref'}]},
 {'given': 'A',
  'family': 'Aulet Ruiz',
  'sequence': 'additional',
  'affiliation': [],
  'role': [{'role': 'author', 'vocabulary': 'crossref'}]}]

In [7]:
authors = item.get("author", [])

authors[0] if authors else None

{'given': 'A',
 'family': 'Pérez-Vázquez',
 'sequence': 'first',
 'affiliation': [],
 'role': [{'role': 'author', 'vocabulary': 'crossref'}]}

In [8]:
author_keys = {}

for item in items:
    for author in item.get("author", []):
        if isinstance(author, dict):
            for key in author.keys():
                author_keys[key] = author_keys.get(key, 0) + 1

sorted(author_keys.items(), key=lambda x: x[1], reverse=True)

[('sequence', 590),
 ('affiliation', 590),
 ('role', 590),
 ('family', 495),
 ('given', 492),
 ('name', 95)]

In [12]:
total_items = len(items)

with_authors = sum(1 for item in items if item.get("author"))
without_authors = total_items - with_authors

with_authors, without_authors

(176, 24)

In [13]:
author_counts = [
    {
        "doi": item.get("DOI"),
        "title": item.get("title", [None])[0] if item.get("title") else None,
        "author_count": len(item.get("author", [])),
    }
    for item in items
]

author_counts_df = pl.DataFrame(author_counts)
author_counts_df.sort("author_count", descending=True).head(10)

shape: (10, 3)
┌─────────────────────────────────┬─────────────────────────────────┬──────────────┐
│ doi                             ┆ title                           ┆ author_count │
│ ---                             ┆ ---                             ┆ ---          │
│ str                             ┆ str                             ┆ i64          │
╞═════════════════════════════════╪═════════════════════════════════╪══════════════╡
│ 10.47870/1519-7522/2021280139-… ┆ HIPERTENSÃO RENOVASCULAR LEVAN… ┆ 18           │
│ 10.47870/1519-7522/2021280148-… ┆ DOENÇA DE CUSHING E HIPERTENSÃ… ┆ 14           │
│ 10.31372/20190403.1056          ┆ Is High Maternal Body Mass Ind… ┆ 14           │
│ 10.32598/jaehr.9.4.1226         ┆ A Simplified Approach to Evalu… ┆ 12           │
│ 10.22203/ecm.v033a11            ┆ A chlorhexidine-releasing epox… ┆ 12           │
│ 10.32598/jaehr.9.4.1243         ┆ Studying the Effluent Quality … ┆ 10           │
│ 10.1157/13053461                ┆ Violencia en la pareja: papel … ┆ 9            │
│ 10.3201/eid2502.181386          ┆ Tick-Borne Encephalitis Virus … ┆ 9            │
│ 10.22203/ecm.v033a10            ┆ Growth plate extracellular mat… ┆ 9            │
│ 10.1157/13053465                ┆ Epidemiología e impacto de la … ┆ 8            │
└─────────────────────────────────┴─────────────────────────────────┴──────────────┘

In [10]:
author_rows = []

for item in items:
    doi = item.get("DOI")

    for author in item.get("author", []):
        if isinstance(author, dict):
            author_rows.append({
                "doi": doi,
                "given": author.get("given"),
                "family": author.get("family"),
                "orcid": author.get("ORCID"),
                "affiliation": author.get("affiliation"),
            })

authors_df = pl.DataFrame(author_rows)

authors_df.head()

shape: (5, 5)
┌──────────────────┬───────┬────────────────┬───────┬─────────────────┐
│ doi              ┆ given ┆ family         ┆ orcid ┆ affiliation     │
│ ---              ┆ ---   ┆ ---            ┆ ---   ┆ ---             │
│ str              ┆ str   ┆ str            ┆ null  ┆ list[struct[1]] │
╞══════════════════╪═══════╪════════════════╪═══════╪═════════════════╡
│ 10.1157/13053457 ┆ A     ┆ Pérez-Vázquez  ┆ null  ┆ []              │
│ 10.1157/13053457 ┆ R     ┆ Vidal Álvarez  ┆ null  ┆ []              │
│ 10.1157/13053457 ┆ M     ┆ Castro Pazos   ┆ null  ┆ []              │
│ 10.1157/13053457 ┆ A     ┆ Aulet Ruiz     ┆ null  ┆ []              │
│ 10.1157/13053459 ┆ A     ┆ Piedra Cerezal ┆ null  ┆ []              │
└──────────────────┴───────┴────────────────┴───────┴─────────────────┘

In [11]:
authors_df.select(
    pl.len().alias("total_author_rows"),
    pl.col("orcid").is_not_null().sum().alias("authors_with_orcid"),
    pl.col("orcid").is_null().sum().alias("authors_without_orcid"),
)

shape: (1, 3)
┌───────────────────┬────────────────────┬───────────────────────┐
│ total_author_rows ┆ authors_with_orcid ┆ authors_without_orcid │
│ ---               ┆ ---                ┆ ---                   │
│ u32               ┆ u32                ┆ u32                   │
╞═══════════════════╪════════════════════╪═══════════════════════╡
│ 590               ┆ 0                  ┆ 590                   │
└───────────────────┴────────────────────┴───────────────────────┘

In [16]:
authors_df.select("affiliation")

shape: (590, 1)
┌─────────────────┐
│ affiliation     │
│ ---             │
│ list[struct[1]] │
╞═════════════════╡
│ []              │
│ []              │
│ []              │
│ []              │
│ []              │
│ …               │
│ []              │
│ []              │
│ []              │
│ []              │
│ []              │
└─────────────────┘

In [19]:
authors_df.filter(
    pl.col("affiliation").list.len() > 0
).select("affiliation")

shape: (5, 1)
┌─────────────────────────────────┐
│ affiliation                     │
│ ---                             │
│ list[struct[1]]                 │
╞═════════════════════════════════╡
│ [{"نائب رئيس البرامج ـ مرکز بح… │
│ [{"مرکز بحوث التنمية الدولية ـ… │
│ [{"Department of Pharmacy, JNT… │
│ [{"Department of Pharmaceutica… │
│ [{"Department of Pharmaceutica… │
└─────────────────────────────────┘

In [5]:
from collections import Counter
import json
from pathlib import Path

#raw_path = Path("../data/raw/crossref_raw_20260614T213935Z_fed79583-82ce-45d7-82fa-6d834d0895d6.json")

with raw_path.open("r", encoding="utf-8") as file:
    payload = json.load(file)

items = payload["message"]["items"]

In [8]:
field = "title"
#field = "container-title"

type_counts = Counter(type(item.get(field)).__name__ for item in items)

type_counts

Counter({'list': 196, 'NoneType': 4})

In [9]:
fields = [
    "title",
    "container-title",
    "short-container-title",
    "original-title",
]

for field in fields:
    type_counts = Counter(type(item.get(field)).__name__ for item in items)
    print(field, type_counts)

title Counter({'list': 196, 'NoneType': 4})
container-title Counter({'list': 197, 'NoneType': 3})
short-container-title Counter({'list': 172, 'NoneType': 28})
original-title Counter({'NoneType': 192, 'list': 8})

In [10]:
field = "title"

length_counts = Counter(
    len(item[field])
    for item in items
    if isinstance(item.get(field), list)
)

length_counts

Counter({1: 196})

In [14]:
field = "original-title"

multi_value_examples = [
    item.get(field)
    for item in items
    if isinstance(item.get(field), list) and len(item[field]) > 1
]

multi_value_examples[:5]

[]

In [15]:
field = "title"

missing_count = sum(1 for item in items if field not in item)
empty_list_count = sum(1 for item in items if item.get(field) == [])

missing_count, empty_list_count

(4, 0)

In [16]:
doi_values = [
    item.get("DOI")
    for item in items
    if item.get("DOI") is not None
]

doi_checks = []

for doi in doi_values:
    doi_checks.append({
        "original": doi,
        "has_outer_spaces": doi != doi.strip(),
        "has_uppercase": doi != doi.lower(),
        "normalized": doi.strip().lower(),
    })

doi_checks[:10]

[{'original': '10.1157/13053457',
  'has_outer_spaces': False,
  'has_uppercase': False,
  'normalized': '10.1157/13053457'},
 {'original': '10.1157/13053459',
  'has_outer_spaces': False,
  'has_uppercase': False,
  'normalized': '10.1157/13053459'},
 {'original': '10.1157/13053456',
  'has_outer_spaces': False,
  'has_uppercase': False,
  'normalized': '10.1157/13053456'},
 {'original': '10.1157/13053452',
  'has_outer_spaces': False,
  'has_uppercase': False,
  'normalized': '10.1157/13053452'},
 {'original': '10.1157/13053449',
  'has_outer_spaces': False,
  'has_uppercase': False,
  'normalized': '10.1157/13053449'},
 {'original': '10.1157/13053460',
  'has_outer_spaces': False,
  'has_uppercase': False,
  'normalized': '10.1157/13053460'},
 {'original': '10.1157/13053448',
  'has_outer_spaces': False,
  'has_uppercase': False,
  'normalized': '10.1157/13053448'},
 {'original': '10.1157/13053451',
  'has_outer_spaces': False,
  'has_uppercase': False,
  'normalized': '10.1157/13053451'},
 {'original': '10.1157/13053458',
  'has_outer_spaces': False,
  'has_uppercase': False,
  'normalized': '10.1157/13053458'},
 {'original': '10.1157/13053723',
  'has_outer_spaces': False,
  'has_uppercase': False,
  'normalized': '10.1157/13053723'}]

In [17]:
problematic_dois = [
    row for row in doi_checks
    if row["has_outer_spaces"] or row["has_uppercase"]
]

problematic_dois

[]

In [18]:
total_dois = len(doi_values)

uppercase_count = sum(1 for doi in doi_values if doi != doi.lower())
outer_space_count = sum(1 for doi in doi_values if doi != doi.strip())

total_dois, uppercase_count, outer_space_count

(200, 0, 0)

In [19]:
import polars as pl

doi_df = pl.DataFrame(doi_checks)

doi_df.filter(
    pl.col("has_outer_spaces") | pl.col("has_uppercase")
)

shape: (0, 4)
┌──────────┬──────────────────┬───────────────┬────────────┐
│ original ┆ has_outer_spaces ┆ has_uppercase ┆ normalized │
│ ---      ┆ ---              ┆ ---           ┆ ---        │
│ str      ┆ bool             ┆ bool          ┆ str        │
╞══════════╪══════════════════╪═══════════════╪════════════╡
└──────────┴──────────────────┴───────────────┴────────────┘